"""
Mid-Term Memory Bridge – export knowledge pills to a local markdown file.

Bridges the Long-Term layer (MongoDB) to the Mid-Term layer (local markdown
files that can be injected as Cursor rules or context). Part of the three-tier
"Tiered Memory" system from the Wave 3 architecture.

Usage:
    python sync_memory.py                                    # default MEMORY.md
    python sync_memory.py --output ~/.cursor/rules/kb.md     # custom path
    python sync_memory.py --categories python,architecture   # filter
    python sync_memory.py --limit 100                        # max pills
"""

from __future__ import annotations

import argparse
import asyncio
import sys
from datetime import datetime, timezone

from db import close, get_collection


async def sync(
    output: str = "MEMORY.md",
    categories: list[str] | None = None,
    limit: int = 50,
) -> None:
    col = await get_collection()

    filter_doc: dict = {"status": "active"}
    if categories:
        filter_doc["category"] = {"$in": categories}

    cursor = (
        col.find(filter_doc, {"embedding": 0})
        .sort([("confidence", -1), ("created_at", -1)])
        .limit(limit)
    )

    pills_by_category: dict[str, list[dict]] = {}
    total = 0
    async for doc in cursor:
        cat = doc["category"]
        if cat not in pills_by_category:
            pills_by_category[cat] = []
        pills_by_category[cat].append(doc)
        total += 1

    if total == 0:
        print("No active pills found. Nothing to export.")
        return

    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        "# Agent Knowledge Base",
        "",
        f"> Auto-generated by sync_memory.py | {now} | {total} pills",
        "> Do not edit manually -- changes will be overwritten on next sync.",
        "",
    ]

    for cat in sorted(pills_by_category.keys()):
        pills = pills_by_category[cat]
        lines.append(f"## {cat} ({len(pills)} pills)")
        lines.append("")

        for pill in pills:
            conf = pill.get("confidence", 1.0)
            tags = ", ".join(pill.get("tags", []))
            lines.append(f"### {pill['title']}")
            lines.append("")
            lines.append(pill["content"])
            lines.append("")
            meta_parts = [f"Confidence: {conf:.2f}"]
            if tags:
                meta_parts.append(f"Tags: {tags}")
            lines.append(f"*{' | '.join(meta_parts)}*")
            lines.append("")

    content = "\n".join(lines)

    with open(output, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Exported {total} pills across {len(pills_by_category)} categories to {output}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Export knowledge pills to markdown (Mid-Term Memory bridge)"
    )
    parser.add_argument(
        "--output", "-o",
        default="MEMORY.md",
        help="Output file path (default: MEMORY.md)",
    )
    parser.add_argument(
        "--categories", "-c",
        default=None,
        help="Comma-separated list of categories to include",
    )
    parser.add_argument(
        "--limit", "-n",
        type=int,
        default=50,
        help="Maximum number of pills to export (default: 50)",
    )
    args = parser.parse_args()

    cats = args.categories.split(",") if args.categories else None

    try:
        asyncio.run(sync(output=args.output, categories=cats, limit=args.limit))
    except KeyboardInterrupt:
        print("\nInterrupted.")
        sys.exit(1)
    finally:
        asyncio.run(close())
